apiVersion: v1
kind: Service
metadata:
  name: octopub-audit-cluster-ip
  labels:
    component: #{Project.Labels.Component}
spec:
  type: ClusterIP
  selector:
    component: #{Project.Labels.Component}
  ports:
    - port: 10000
      targetPort: 10000
      name: http-audit